---
# tasks file for ansible-role-kafka
- name: Set some role facts
  include_tasks: gather_role_facts.yml
  tags:
    - role_facts

- name: Install dependency packages
  ansible.builtin.package:
    name: "{{ _kafka_broker_packages }}"
    update_cache: true
    state: present
  tags:
    - packages

- name: Stat the destination dir
  ansible.builtin.stat:
    path: "{{ kafka_broker_prefix }}"
  register: _kafka_broker_st
  tags:
    - install

- name: Load the checksum
  ansible.builtin.slurp:
    path: "{{ kafka_broker_prefix }}/.kafka_broker_ansible_checksum"
  failed_when: false
  register: _checksum
  tags:
    - install

- name: Create destination dir
  ansible.builtin.file:
    path: "{{ kafka_broker_prefix }}"
    state: directory
    owner: "{{ kafka_broker_user | default('root') }}"
    group: "{{ kafka_broker_group | default('root') }}"
    # Default directories: 0755, files: 0644
    mode: "{{ kafka_broker_mode | default('u+rwX,go+rX,go-w') }}"
  when:
    - "not _kafka_broker_st.stat.exists"
  tags:
    - install

- block:
    - name: Create a tmpdir for the archive
      ansible.builtin.tempfile:
        state: directory
      register: _archive_tmpdir
      changed_when: false

    - name: Create a tmpdir for the extracted resources
      ansible.builtin.tempfile:
        state: directory
      register: _resources_tmpdir
      changed_when: false

    - name: Download archive
      ansible.builtin.get_url:
        url: "{{ kafka_broker_release_src }}"
        dest: "{{ _archive_tmpdir.path }}/{{ kafka_broker_release_src | basename }}"
        checksum: "{{ kafka_broker_release_checksum | default(omit) }}"

    - name: Get the archive checksum
      ansible.builtin.stat:
        path: "{{ _archive_tmpdir.path }}/{{ kafka_broker_release_src | basename }}"
      register: _src_st

    - name: Extract the archive
      ansible.builtin.unarchive:
        src: "{{ _archive_tmpdir.path }}/{{ kafka_broker_release_src | basename }}"
        dest: "{{ _resources_tmpdir.path }}"
        owner: "{{ kafka_broker_user }}"
        group: "{{ kafka_broker_group }}"
        remote_src: "{{ kafka_broker_release_remote_src | bool }}"
      register: _extraction

    - name: Output the appropriate checksum
      ansible.builtin.copy:
        content: "{{ _src_st.stat.checksum }}"
        dest: >-
          {{ _resources_tmpdir.path }}/{{ kafka_broker_release_src | basename |
          regex_replace('.tgz$', '') }}/.kafka_broker_ansible_checksum

    - name: Synchronize tmpdir over to the prefix dir
      ansible.builtin.synchronize:
        src: >-
          {{ _resources_tmpdir.path }}/{{ kafka_broker_release_src | basename |
          regex_replace('.tgz$', '') }}/
        dest: "{{ kafka_broker_prefix }}/"
        owner: true
        group: true
      delegate_to: "{{ inventory_hostname }}"
  always:
    - name: Cleanup tmpdir
      file:
        path: "{{ _archive_tmpdir.path }}"
        state: absent
      changed_when: false

    - name: Cleanup tmpdir
      file:
        path: "{{ _resources_tmpdir.path }}"
        state: absent
      changed_when: false
  when:
    - >-
      ('content' is not in _checksum) or
      (
        (kafka_broker_release_checksum is not none) and
        ((_checksum.content | b64decode) != kafka_broker_release_checksum)
      )

- name: Create log dirs
  ansible.builtin.file:
    path: "{{ __kb_logdir }}"
    state: directory
    owner: "{{ kafka_owner }}"
    group: "{{ kafka_group }}"
    mode: "0700"
  loop: "{{ kafka_broker_log_dirs }}"
  loop_control:
    loop_var: "__kb_logdir"
  when:
    - "kafka_broker_create_log_dirs|bool"

- block:
    - name: Install zookeeper service config
      include_tasks: install-zookeeper-service.yml
      when:
        - "kafka_broker_zookeeper_service_enabled|bool"

    - name: Install kafka service config
      include_tasks: install-kafka-service.yml
